server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: user-management-auth
          uri: lb://user-management-service
          predicates:
            - Path=/api/auth/**
        - id: user-management-service
          uri: lb://user-management-service
          predicates:
            - Path=/api/users/**
        - id: shipment-service
          uri: lb://shipment-service
          predicates:
            - Path=/api/shipments/**

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

logging:
  level:
    com.netflix.discovery: DEBUG
