spring.application.name=shipment-service

# Config Server Settings
spring.cloud.config.enabled=false
spring.cloud.config.import-check.enabled=false

# Database Configuration
# Docker üzerinde çalışırken postgres hostname'i kullanılır
# Lokal çalıştırırken localhost kullanılır
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5433/cargotracking}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:1234}
spring.datasource.driver-class-name=org.postgresql.Driver

# HikariCP Configuration  
spring.datasource.hikari.connection-timeout=60000
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.idle-timeout=300000

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Server Configuration
server.port=8082

# Eureka Client Configuration
# Docker üzerinde çalışırken eureka-server hostname'i kullanılır
# Lokal çalıştırırken localhost kullanılır
eureka.client.service-url.defaultZone=${EUREKA_URL:http://localhost:8761/eureka/}
eureka.instance.preferIpAddress=true
