FROM openjdk:17-jdk-slim

# Uygulama klasörü oluştur
WORKDIR /app

# Maven wrapper ve pom.xml dosyalarını kopyala
COPY .mvn/ .mvn
COPY mvnw pom.xml ./

# Bağımlılıkları indir (cache için)
RUN chmod +x ./mvnw && ./mvnw dependency:go-offline

# Kaynak kodları kopyala
COPY src ./src

# Uygulamayı derle
RUN ./mvnw package -DskipTests

# JAR dosyasını çalıştır
EXPOSE 8761
ENTRYPOINT ["java", "-jar", "target/eureka-server-1.0.0.jar"] 