spring:
  application:
    name: tracking-service
  config:
    import: "configserver:${CONFIG_SERVER_URL:http://config-server:8888}"
  cloud:
    config:
      enabled: true
      uri: ${CONFIG_SERVER_URL:http://config-server:8888}
      fail-fast: true
      retry:
        initial-interval: 1000
        max-attempts: 6
        max-interval: 2000

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://eureka-server:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.cloud.config: DEBUG
    com.cargotracking: DEBUG