spring.application.name=tracking-service

# Config Server Settings
spring.cloud.config.enabled=false
spring.cloud.config.import-check.enabled=false

# MongoDB Configuration
# Docker üzerinde çalışırken mongodb hostname'i kullanılır
# Lokal çalıştırırken localhost kullanılır
spring.data.mongodb.uri=${MONGODB_URL:mongodb://localhost:27017/tracking_db}

# Redis Configuration
# Docker üzerinde çalışırken redis hostname'i kullanılır
# Lokal çalıştırırken localhost kullanılır
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}

# Server Configuration
server.port=8083

# Eureka Client Configuration
# Docker üzerinde çalışırken eureka-server hostname'i kullanılır
# Lokal çalıştırırken localhost kullanılır
eureka.client.service-url.defaultZone=${EUREKA_URL:http://localhost:8761/eureka/}
eureka.instance.preferIpAddress=true
