spring.application.name=eureka-server

# Config Server Settings
spring.cloud.config.enabled=false
spring.cloud.config.import-check.enabled=false

# Server Configuration
server.port=8761

# Eureka Configuration - Standalone Mode
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.hostname=localhost
eureka.server.enable-self-preservation=false
