server:
  port: 0

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/userdb
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

jwt:
  secret: MySuperSecretKey
