server:
  port: 8888

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/userdb
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: file:///${user.dir}/../config-repo
          searchPaths: .

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

jwt:
  secret: MySuperSecretKey
